version: '3.8'
services:
  postgres:
    restart: always
    build: 
      context: .
      dockerfile: postgres/Dockerfile
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - postgres-network
volumes:
  db:
    driver: local
networks:
  postgres-network:
    driver: bridge