version: '3.8'
services:
  postgres:
    image: postgres:12.0
    restart: always
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local